export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FACULTY_LOADED = 'FACULTY_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_EVENT = 'GET_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';
export const GET_CURRENT_EVENT  = 'GET_CURRENT_EVENT';
export const CURRENT_EVENT_ERROR= 'CURRENT_EVENT_ERROR';

//SURVEY
export const SURVEY_GET_SUCCESS = 'SURVEY_SUCCESS';
export const SURVEY_GET_FAILURE = 'SURVEY_FAILURE';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const SURVEY_RESPONSE_SUCCESS = 'SURVEY_RESPONSE_SUCCESS';
export const SURVEY_RESPONSE_FAIL = 'SURVEY_RESPONSE_FAIL';
export const GET_SURVEY_RESP_SUCCESS = 'GET_SURVEY_RESP_SUCCESS';
export const GET_SURVEY_RESP_FAIL = 'GET_SURVEY_RESP_FAIL';
export const SET_SURVEY_DATES_SUCCESS = 'SET_SURVEY_DATES_SUCCESS';
export const SET_SURVEY_DATES_FAIL = 'SET_SURVEY_DATES_FAIL';
export const GET_SURVEY_PUBLISH_DATE = 'GET_SURVEY_PUBLISH_DATE';
export const GET_SURVEY_END_DATE = 'GET_SURVEY_END_DATE';
export const GET_SURVEY_DATE_FAIL = 'GET_SURVEY_DATE_FAIL';


//student grade 
export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const GET_STUDENT_PROFILES = 'GET_STUDENT_PROFILES';
export const STUDENT_PROFILE_ERROR = 'STUDENT_PROFILE_ERROR';
export const CLEAR_STUDENT_PROFILE = 'CLEAR STUDENT PROFILE';
export const STUDENT_ACCOUNT_DELETED = 'STUDENT_ACCOUNT_DELETED';
export const UPDATE_STUDENT_PROFILE = 'UPDATE_STUDENT_PROFILE';
