// AUTH
export const USER_LOADED = 'USER_LOADED';
// export const ALL_USERS_LOADED = 'ALL_USERS_LOADED';
export const SET_AUTH_USER_LOADING = 'SET_AUTH_USER_LOADING';
export const UNSET_AUTH_USER_LOADING = 'UNSET_AUTH_USER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const NAME_UPDATED = 'NAME_UPDATED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED';
export const PROFILE_PICTURE_REMOVED = 'PROFILE_PICTURE_REMOVED';

// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// ADMISSIONS
export const CURRENT_SESSION_LOADED = 'CURRENT_SESSION_LOADED';
export const ALL_ADMISSION_SESSIONS_LOADED = 'ALL_ADMISSION_SESSIONS_LOADED';
export const ADMISSION_SESSION_CREATED = 'ADMISSION_SESSION_CREATED';
export const ADMISSION_SESSION_UPDATED = 'ADMISSION_SESSION_UPDATED';
export const ADMISSION_SESSION_ERROR = 'ADMISSION_SESSION_ERROR';
export const ADMISSION_SESSION_ENABLED = 'ADMISSION_SESSION_ENABLED';
export const ADMISSION_SESSION_DISABLED = 'ADMISSION_SESSION_DISABLED';
export const ADMISSION_SESSION_LOADING = 'ADMISSION_SESSION_LOADING';
export const ADMISSION_SESSION_LOADED = 'ADMISSION_SESSION_LOADED';
export const ADMISSION_SESSION_REMOVED = 'ADMISSION_SESSION_REMOVED';
// export const ADMISSION_SESSION_ANNOUNCEMENT_UPDATED =
//   'ADMISSION_SESSION_ANNOUNCEMENT_UPDATED';

// ADMISSION_LIST
export const GET_MERIT_LIST = 'GET_MERIT_LIST';
export const GENERATE_ADMISSION_MERIT_LIST = 'GENERATE_ADMISSION_MERIT_LIST';

// ENROLLMENTS
export const CURRENT_SEMESTER_LOADED = 'CURRENT_SEMESTER_LOADED';
export const ALL_ENROLLMENT_SEMESTERS_LOADED =
  'ALL_ENROLLMENT_SEMESTERS_LOADED';
export const ENROLLMENT_SEMESTER_CREATED = 'ENROLLMENT_SEMESTER_CREATED';
export const ENROLLMENT_SEMESTER_UPDATED = 'ENROLLMENT_SEMESTER_UPDATED';
export const ENROLLMENT_SEMESTER_ERROR = 'ENROLLMENT_SEMESTER_ERROR';
export const ENROLLMENT_SEMESTER_ENABLED = 'ENROLLMENT_SEMESTER_ENABLED';
export const ENROLLMENT_SEMESTER_DISABLED = 'ENROLLMENT_SEMESTER_DISABLED';
export const ENROLLMENT_SEMESTER_LOADING = 'ENROLLMENT_SEMESTER_LOADING';
export const ENROLLMENT_SEMESTER_LOADED = 'ENROLLMENT_SEMESTER_LOADED';
export const ENROLLMENT_SEMESTER_REMOVED = 'ENROLLMENT_SEMESTER_REMOVED';

// ENROLLMENT_COURSE_LIST
export const GET_COURSE_LIST = 'GET_COURSE_LIST';
export const GENERATE_ENROLLMENT_COURSE_LIST =
  'GENERATE_ENROLLMENT_COURSE_LIST';

// ENROLLMENT_SECTION_LIST
export const GET_SECTION_LIST = 'GET_SECTION_LIST';
export const GENERATE_ENROLLMENT_SECTION_LIST =
  'GENERATE_ENROLLMENT_SECTION_LIST';

// ANNOUNCEMENTS
export const CURRENT_ANNOUNCEMENT_FEED_LOADED =
  'CURRENT_ANNOUNCEMENT_FEED_LOADED';
export const ALL_ANNOUNCEMENT_FEEDS_LOADED = 'ALL_ANNOUNCEMENT_FEEDS_LOADED';
export const ANNOUNCEMENT_FEED_LOADING = 'ANNOUNCEMENT_FEED_LOADING';
export const ANNOUNCEMENT_FEED_LOADED = 'ANNOUNCEMENT_FEED_LOADED';
export const ANNOUNCEMENT_FEED_CREATED = 'ANNOUNCEMENT_FEED_CREATED';
export const ANNOUNCEMENT_FEED_ENABLED = 'ANNOUNCEMENT_FEED_ENABLED';
export const ANNOUNCEMENT_FEED_DISABLED = 'ANNOUNCEMENT_FEED_DISABLED';
export const ANNOUNCEMENT_FEED_REMOVED = 'ANNOUNCEMENT_FEED_REMOVED';
export const ANNOUNCEMENT_FEED_UPDATED = 'ANNOUNCEMENT_FEED_UPDATED';
export const ANNOUNCEMENT_FEED_ERROR = 'ANNOUNCEMENT_FEED_ERROR';

// DEPARTMENTS
export const ALL_DEPARTMENTS_LOADED = 'ALL_DEPARTMENTS_LOADED';
export const DEPARTMENT_LOADED = 'DEPARTMENT_LOADED';
export const DEPARTMENT_CREATED = 'DEPARTMENT_CREATED';
export const DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED';
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR';

// SECTIONS
export const ALL_SECTIONS_LOADED = 'ALL_SECTIONS_LOADED';
export const SECTION_LOADED = 'SECTION_LOADED';
export const SECTION_CREATED = 'SECTION_CREATED';
export const SECTION_UPDATED = 'SECTION_UPDATED';
export const SECTION_ERROR = 'SECTION_ERROR';
export const SECTION_REMOVED = 'SECTION_REMOVED';

// PROGRAMS
export const PROGRAM_LOADED = 'PROGRAM_LOADED';
export const PROGRAM_ERROR = 'PROGRAM_ERROR';
export const REMOVE_PROGRAM = 'REMOVE_PROGRAM';
export const ALL_PROGRAMS_LOADED = 'ALL_PROGRAMS_LOADED';

// UNDERGRADUATE_PROGRAMS
export const ALL_UNDERGRADUATE_PROGRAMS_LOADED =
  'ALL_UNDERGRADUATE_PROGRAMS_LOADED';
export const UNDERGRADUATE_PROGRAM_CREATED = 'UNDERGRADUATE_PROGRAM_CREATED';
export const UNDERGRADUATE_PROGRAM_UPDATED = 'UNDERGRADUATE_PROGRAM_UPDATED';
export const SET_UNDERGRADUATE_PROGRAM_LOADING =
  'SET_UNDERGRADUATE_PROGRAM_LOADING';
export const UNDERGRADUATE_PROGRAM_ENABLED = 'UNDERGRADUATE_PROGRAM_ENABLED';
export const UNDERGRADUATE_PROGRAM_DISABLED = 'UNDERGRADUATE_PROGRAM_DISABLED';
export const ALL_UNDERGRADUATE_PROGRAMS_DISABLED =
  'ALL_UNDERGRADUATE_PROGRAMS_DISABLED';
export const DEPARTMENT_UNDERGRADUATE_PROGRAMS_LOADED =
  'DEPARTMENT_UNDERGRADUATE_PROGRAMS_LOADED';

// GRADUATE_PROGRAMS
export const ALL_GRADUATE_PROGRAMS_LOADED = 'ALL_GRADUATE_PROGRAMS_LOADED';
export const GRADUATE_PROGRAM_CREATED = 'GRADUATE_PROGRAM_CREATED';
export const GRADUATE_PROGRAM_UPDATED = 'GRADUATE_PROGRAM_UPDATED';
export const SET_GRADUATE_PROGRAM_LOADING = 'SET_GRADUATE_PROGRAM_LOADING';
export const GRADUATE_PROGRAM_ENABLED = 'GRADUATE_PROGRAM_ENABLED';
export const GRADUATE_PROGRAM_DISABLED = 'GRADUATE_PROGRAM_DISABLED';
export const DEPARTMENT_GRADUATE_PROGRAMS_LOADED =
  'DEPARTMENT_GRADUATE_PROGRAMS_LOADED';

// COURSES
export const COURSE_LOADED = 'COURSE_LOADED';
export const COURSE_ERROR = 'COURSE_ERROR';
export const REMOVE_COURSE = 'REMOVE_COURSE';

// UNDERGRADUATE_COURSES
export const ALL_UNDERGRADUATE_COURSES_LOADED =
  'ALL_UNDERGRADUATE_COURSES_LOADED';
export const UNDERGRADUATE_COURSE_MAJOR_CREATED =
  'UNDERGRADUATE_COURSE_MAJOR_CREATED';
export const UNDERGRADUATE_COURSE_MINOR_CREATED =
  'UNDERGRADUATE_COURSE_MINOR_CREATED';
export const UNDERGRADUATE_COURSE_UPDATED = 'UNDERGRADUATE_COURSE_UPDATED';
export const SET_UNDERGRADUATE_COURSE_LOADING =
  'SET_UNDERGRADUATE_COURSE_LOADING';
export const UNDERGRADUATE_COURSE_ENABLED = 'UNDERGRADUATE_COURSE_ENABLED';
export const UNDERGRADUATE_COURSE_DISABLED = 'UNDERGRADUATE_COURSE_DISABLED';
export const ALL_UNDERGRADUATE_COURSES_DISABLED =
  'ALL_UNDERGRADUATE_COURSES_DISABLED';
export const PROGRAM_UNDERGRADUATE_COURSES_LOADED =
  'PROGRAM_UNDERGRADUATE_COURSES_LOADED';
export const SECTION_UNDERGRADUATE_COURSES_LOADED =
  'SECTION_UNDERGRADUATE_COURSES_LOADED';

// GRADUATE_COURSES
export const ALL_GRADUATE_COURSES_LOADED = 'ALL_GRADUATE_COURSES_LOADED';
export const GRADUATE_COURSE_MAJOR_CREATED = 'GRADUATE_COURSE_MAJOR_CREATED';
export const GRADUATE_COURSE_MINOR_CREATED = 'GRADUATE_COURSE_MINOR_CREATED';
export const GRADUATE_COURSE_UPDATED = 'GRADUATE_COURSE_UPDATED';
export const SET_GRADUATE_COURSE_LOADING = 'SET_GRADUATE_COURSE_LOADING';
export const GRADUATE_COURSE_ENABLED = 'GRADUATE_COURSE_ENABLED';
export const GRADUATE_COURSE_DISABLED = 'GRADUATE_COURSE_DISABLED';
export const ALL_GRADUATE_COURSES_DISABLED = 'ALL_GRADUATE_COURSES_DISABLED';
export const PROGRAM_GRADUATE_COURSES_LOADED =
  'PROGRAM_GRADUATE_COURSES_LOADED';
export const SECTION_GRADUATE_COURSES_LOADED =
  'SECTION_GRADUATE_COURSES_LOADED';

// PROFILES

// ADMIN_PROFILE_DETAILS
export const SET_ADMIN_PROFILE_LOADING = 'SET_ADMIN_PROFILE_LOADING';
export const ADMIN_PROFILE_LOADED = 'ADMIN_PROFILE_LOADED';
export const ADMIN_PROFILES_LOADED = 'ADMIN_PROFILES_LOADED';
export const UPDATE_ADMIN_PERSONAL_DETAILS = 'UPDATE_ADMIN_PERSONAL_MY_DETAILS';
export const UPDATE_ADMIN_EXPERIENCE_DETAILS =
  'UPDATE_ADMIN_EXPERIENCE_DETAILS';
export const UPDATE_ADMIN_EDUCATION_DETAILS = 'UPDATE_ADMIN_EDUCATION_DETAILS';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';
export const CLEAR_ADMIN_PROFILE = 'CLEAR_ADMIN_PROFILE';

// COORDINATOR_PROFILE_DETAILS
export const SET_COORDINATOR_PROFILE_LOADING =
  'SET_COORDINATOR_PROFILE_LOADING';
export const COORDINATOR_PROFILE_LOADED = 'COORDINATOR_PROFILE_LOADED';
export const COORDINATOR_PROFILES_LOADED = 'COORDINATOR_PROFILES_LOADED';
export const UPDATE_COORDINATOR_PERSONAL_DETAILS =
  'UPDATE_COORDINATOR_PERSONAL_MY_DETAILS';
export const UPDATE_COORDINATOR_EXPERIENCE_DETAILS =
  'UPDATE_COORDINATOR_EXPERIENCE_DETAILS';
export const UPDATE_COORDINATOR_EDUCATION_DETAILS =
  'UPDATE_COORDINATOR_EDUCATION_DETAILS';
export const COORDINATOR_PROFILE_ERROR = 'COORDINATOR_PROFILE_ERROR';
export const CLEAR_COORDINATOR_PROFILE = 'CLEAR_COORDINATOR_PROFILE';

// COORDINATOR
export const ALL_COORDINATORS_LOADED = 'ALL_COORDINATORS_LOADED';
export const ALL_DEPARTMENT_COORDINATORS_LOADED =
  'ALL_DEPARTMENT_COORDINATORS_LOADED';
export const COORDINATOR_LOADED = 'COORDINATOR_LOADED';
export const REGISTER_COORDINATOR_SUCCESS = 'REGISTER_COORDINATOR_SUCCESS';
export const REGISTER_COORDINATOR_FAILED = 'REGISTER_COORDINATOR_FAILED';
export const COORDINATORS_ERROR = 'COORDINATOR_ERROR';
export const COORDINATOR_NAME_UPDATED = 'COORDINATOR_NAME_UPDATED';
export const COORDINATOR_PASSWORD_UPDATED = 'COORDINATOR_PASSWORD_UPDATED';
export const COORDINATOR_PROFILE_PICTURE_UPDATED =
  'COORDINATOR_PROFILE_PICTURE_UPDATED';
export const COORDINATOR_PROFILE_PICTURE_REMOVED =
  'COORDINATOR_PROFILE_PICTURE_REMOVED';
export const SET_AUTH_COORDINATOR_LOADING = 'SET_AUTH_COORDINATOR_LOADING';
export const UNSET_AUTH_COORDINATOR_LOADING = 'UNSET_AUTH_COORDINATOR_LOADING';
export const DELETE_COORDINATOR_ACCOUNT = 'DELETE_COORDINATOR_ACCOUNT';

// STUDENT
export const ALL_UNDERGRADUATE_STUDENTS_LOADED =
  'ALL_UNDERGRADUATE_STUDENTS_LOADED';
export const UNDERGRADUATE_STUDENT_LOADED = 'UNDERGRADUATE_STUDENT_LOADED';
export const REGISTER_UNDERGRADUATE_STUDENT_SUCCESS =
  'REGISTER_UNDERGRADUATE_STUDENT_SUCCESS';
export const REGISTER_UNDERGRADUATE_STUDENT_FAILED =
  'REGISTER_UNDERGRADUATE_STUDENT_FAILED';
export const UNDERGRADUATE_STUDENTS_ERROR = 'UNDERGRADUATE_STUDENT_ERROR';
// export const SET_AUTH_STUDENT_LOADING = 'SET_AUTH_STUDENT_LOADING';
// export const UNSET_AUTH_STUDENT_LOADING = 'UNSET_AUTH_STUDENT_LOADING';
// export const DELETE_STUDENT_ACCOUNT = 'DELETE_STUDENT_ACCOUNT';

// APPLICANTS
export const APPLICANT_LOADED = 'APPLICANT_LOADED';
export const APPLICANT_ERROR = 'APPLICANT_ERROR';
export const APPLICANT_PROGRAM_APPLIED = 'APPLICANT_PROGRAM_APPLIED';
export const APPLICANT_PROGRAM_REMOVED = 'APPLICANT_PROGRAM_REMOVED';
export const APPLICANT_COURSE_REGISTERED = 'APPLICANT_COURSE_REGISTERED';
export const APPLICANT_COURSE_REMOVED = 'APPLICANT_COURSE_REMOVED';
export const APPLICANT_FORWARDED = 'APPLICANT_FORWARDED';
export const APPLICANT_FORWARDED_LOADED = 'APPLICANT_FORWARDED_LOADED';
export const SET_APPLICANT_LOADING = 'SET_APPLICANT_LOADING';
export const APPLICANT_TEST_SCORE_ADDED = 'APPLICANT_TEST_SCORE_ADDED';
export const APPLICANT_ADMISSION_FEE_PICTURE_ADDED =
  'APPLICANT_ADMISSION_FEE_PICTURE_ADDED';

// UNDERGRADUATE_APPLICANTS
export const ALL_UNDERGRADUATE_APPLICANT_LOADED =
  'ALL_UNDERGRADUATE_APPLICANT_LOADED';
export const UNDERGRADUATE_APPLICANT_PERSONAL_DETAILS_UPDATED =
  'UNDERGRADUATE_APPLICANT_PERSONAL_DETAILS_UPDATED';
export const UNDERGRADUATE_APPLICANT_INCOME_DETAILS_UPDATED =
  'UNDERGRADUATE_APPLICANT_INCOME_DETAILS_UPDATED';
export const UNDERGRADUATE_APPLICANT_EDUCATION_DETAILS_UPDATED =
  'UNDERGRADUATE_APPLICANT_EDUCATION_DETAILS_UPDATED';
export const UNDERGRADUATE_PROGRAM_APPLIED = 'UNDERGRADUATE_PROGRAM_APPLIED';
export const UNDERGRADUATE_AGGREGATE_CALCULATED =
  'UNDERGRADUATE_AGGREGATE_CALCULATED';
export const UNDERGRADUATE_APPLICATION_FORWARDED =
  'UNDERGRADUATE_APPLICATION_FORWARDED';
// export const UNDERGRADUATE_APPLICANT_APPLIED_PROGRAMS_LOADED =
//   'UNDERGRADUATE_APPLICANT_APPLIED_PROGRAMS_LOADED';
export const UNDERGRADUATE_APPLICANT_VERIFIED =
  'UNDERGRADUATE_APPLICANT_VERIFIED';
export const UNDERGRADUATE_APPLICANT_PENDING =
  'UNDERGRADUATE_APPLICANT_PENDING';
export const UNDERGRADUATE_APPLICANT_DISCARDED =
  'UNDERGRADUATE_APPLICANT_DISCARDED';
export const UNDERGRADUATE_APPLICANT_ACQUIRED =
  'UNDERGRADUATE_APPLICANT_ACQUIRED';

// GRADUATE_APPLICANTS
export const ALL_GRADUATE_APPLICANT_LOADED = 'ALL_GRADUATE_APPLICANT_LOADED';
export const GRADUATE_APPLICANT_PERSONAL_DETAILS_UPDATED =
  'GRADUATE_APPLICANT_PERSONAL_DETAILS_UPDATED';
export const GRADUATE_APPLICANT_INCOME_DETAILS_UPDATED =
  'GRADUATE_APPLICANT_INCOME_DETAILS_UPDATED';
export const GRADUATE_APPLICANT_EDUCATION_DETAILS_UPDATED =
  'GRADUATE_APPLICANT_EDUCATION_DETAILS_UPDATED';
export const GRADUATE_APPLICANT_NTS_MARKS_UPDATED =
  'GRADUATE_APPLICANT_NTS_MARKS_UPDATED';
export const GRADUATE_PROGRAM_APPLIED = 'GRADUATE_PROGRAM_APPLIED';
export const GRADUATE_APPLICANT_VERIFIED = 'GRADUATE_APPLICANT_VERIFIED';
export const GRADUATE_APPLICANT_PENDING = 'GRADUATE_APPLICANT_PENDING';
export const GRADUATE_APPLICANT_DISCARDED = 'GRADUATE_APPLICANT_DISCARDED';
export const GRADUATE_APPLICANT_ACQUIRED = 'GRADUATE_APPLICANT_ACQUIRED';

//Academic record Student profile 

//student profile
export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const GET_STUDENT_PROFILES = 'GET_STUDENT_PROFILES';
export const STUDENT_PROFILE_ERROR = 'STUDENT_PROFILE_ERROR';
export const CLEAR_STUDENT_PROFILE = 'CLEAR_STUDENT_PROFILE';
export const STUDENT_ACCOUNT_DELETED = 'STUDENT_ACCOUNT_DELETED';
export const UPDATE_STUDENT_PROFILE = 'UPDATE_STUDENT_PROFILE';

//FACULTY

//Faculty Center
export const FACULTY_LOADED= 'FACULTY_LOADED';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_EVENT = 'GET_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';
export const GET_FACULTIES = 'GET_FACULTIES';
export const GET_FACULTIES_FAIL = 'GET_FACULTIES_FAIL';
export const GET_CURRENT_FACULTY = 'GET_CURRENT_FACULTY';
export const GET_CURRENT_FACULTY_FAIL= 'GET_CURRENT_FACULTY_FAIL';
export const REGISTER_FACULTY_SUCCESS = 'REGISTER_FACULTY_SUCCESS';
export const REGISTER_FACULTY_FAILED = 'REGISTER_FACULTY_FAILED';
//CHATBOT
export const EMAIL_SENT = 'EMAIL_SENT';
export const EMAIL_FAIL = 'EMAIL_FAIL';


//SURVEYS
export const SURVEY_GET_SUCCESS = 'SURVEY_SUCCESS';
export const SURVEY_GET_FAILURE = 'SURVEY_FAILURE';
export const GET_SURVEYS_SUCCESS = 'GET_SURVEYS_SUCCESS';
export const SURVEY_RESPONSE_SUCCESS = 'SURVEY_RESPONSE_SUCCESS';
export const SURVEY_RESPONSE_FAIL = 'SURVEY_RESPONSE_FAIL';
export const GET_SURVEY_RESP_SUCCESS = 'GET_SURVEY_RESP_SUCCESS';
export const GET_SURVEY_RESP_FAIL = 'GET_SURVEY_RESP_FAIL';
export const SET_SURVEY_DATES_SUCCESS = 'SET_SURVEY_DATES_SUCCESS';
export const SET_SURVEY_DATES_FAIL = 'SET_SURVEY_DATES_FAIL';
export const GET_SURVEY_PUBLISH_DATE = 'GET_SURVEY_PUBLISH_DATE';
export const GET_SURVEY_END_DATE = 'GET_SURVEY_END_DATE';
export const GET_SURVEY_DATE_FAIL = 'GET_SURVEY_DATE_FAIL';